name: pos_printer_manager
description: "A service for printing receipts and labels using various printers."
publish_to: none
version: 0.7.0+2026022001

environment:
  sdk: ^3.10.1
  flutter: ">=3.38.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.5.3
  uuid: ^4.5.2

  pos_printers:
    git:
      url: https://github.com/KickNext/pos_printers.git
      ref: 4332bf72fb2909c111690ccc46edc1f13c7d265b

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  shared_preferences_platform_interface: ^2.4.1
  intl_utils: ^2.8.0

flutter:
  generate: true

flutter_intl:
  enabled: true
  class_name: PrinterManagerL10n
  main_locale: en_US
